services:

  postgres:
    restart: always
    container_name: "postgres"
    hostname: postgres
    image: 'postgres:16.1-alpine'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"

volumes:
  postgres:
    driver: local