spring:
  application:
    name: team-control
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5435/it-profiles
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081