CREATE TABLE IF NOT EXISTS t_hard_specializations
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialization_name VARCHAR(50)                         NOT NULL UNIQUE,

    role_id             BIGINT REFERENCES t_hard_roles (id) NOT NULL
);