CREATE TABLE IF NOT EXISTS t_t_shape_profiles
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_number         VARCHAR(50),
    is_position_current BOOLEAN,

    worker_id           BIGINT REFERENCES t_workers (id)   NOT NULL,
    position_id         BIGINT REFERENCES t_positions (id) NOT NULL
);