CREATE TABLE IF NOT EXISTS t_specializations_competencies
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    specialization_id BIGINT REFERENCES t_hard_specializations (id)             NOT NULL,
    competencion_id       BIGINT REFERENCES t_competencies (id) NOT NULL,

    UNIQUE (specialization_id, competencion_id)
);