CREATE TABLE IF NOT EXISTS t_workers_hard_grades
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    worker_id             BIGINT REFERENCES t_workers (id)             NOT NULL,
    hard_skill_id         BIGINT REFERENCES t_workers_hard_skills (id) NOT NULL,
    competencion_theory_level_id BIGINT REFERENCES t_competencies_levels (id) NOT NULL,
    competencion_practical_level_id BIGINT REFERENCES t_competencies_levels (id) NOT NULL,

    UNIQUE (worker_id, hard_skill_id, competencion_theory_level_id),
    UNIQUE (worker_id, hard_skill_id,competencion_practical_level_id)
);