TRUNCATE t_categories RESTART IDENTITY CASCADE;

INSERT INTO t_categories (category_name)
VALUES ('Иностранные языки'),
       ('APIs-protocols-standarts'),
       ('Нотации моделирования'),
       ('Архитектуры информационных систем'),
       ('Документация-Требования'),
       ('Техники анализа рынков и конкурентов'),
       ('Моделирование информационных систем'),
       ('UX/UI '),
       ('Языки программирования'),
       ('Основы методологий ведения проектов'),
       ('Мониторинг'),
       ('Базы Данных'),
       ('Логирование'),
       ('Контейнеризация'),
       ('Документирование'),
       ('CI/CD - VCS - RHS'),
       ('Операционные системы'),
       ('Брокеры сообщений'),
       ('Frameworks'),
       ('Тестирование'),
       ('Мышление'),
       ('Личная эффективность'),
       ('Коммуникация'),
       ('Управленческие навыки');

TRUNCATE t_competencies RESTART IDENTITY CASCADE;

INSERT INTO t_competencies (competencion_name, is_hard, category_id)
VALUES ('Английский язык', TRUE, 1),
       ('Немецкий язык', TRUE, 1),
       ('REST', TRUE, 2),
       ('JSON APIs', TRUE, 2),
       ('SOAP', TRUE, 2),
       ('JWT', TRUE, 2),
       ('HTTP/s', TRUE, 2),
       ('OAuth', TRUE, 2),
       ('RPC', TRUE, 2),
       ('TCP/IP', TRUE, 2),
       ('BPMN', TRUE, 3),
       ('UML', TRUE, 3),
       ('EPC', TRUE, 3),
       ('Archimate', TRUE, 3),
       ('Микросервисная архитектура', TRUE, 4),
       ('Монолитная', TRUE, 4),
       ('SOA', TRUE, 4),
       ('ESB', TRUE, 4),
       ('Event-streaming', TRUE, 4),
       ('Бизнес-требования', TRUE, 5),
       ('Требования пользователей', TRUE, 5),
       ('Функциональные требования', TRUE, 5),
       ('Системные требования', TRUE, 5),
       ('Бизнес-правила', TRUE, 5),
       ('Нефункциональные требования', TRUE, 5),
       ('Характеристика продукта', TRUE, 5),
       ('SWOT', TRUE, 6),
       ('PEST', TRUE, 6),
       ('5 сил Портера', TRUE, 6),
       ('PAM-ТАМ-SAM-SOM', TRUE, 6),
       ('Канва бизнес-модели', TRUE, 6),
       ('DFD', TRUE, 7),
       ('ERD', TRUE, 7),
       ('Figma', TRUE, 8),
       ('Sketch', TRUE, 8),
       ('Visio', TRUE, 8),
       ('Adobe XD', TRUE, 8),
       ('Material UI', TRUE, 8),
       ('Bootstrap', TRUE, 8),
       ('C\C++', TRUE, 9),
       ('Python', TRUE, 9),
       ('С#', TRUE, 9),
       ('Go', TRUE, 9),
       ('Bash', TRUE, 9),
       ('Java', TRUE, 9),
       ('JavaScript', TRUE, 9),
       ('TypeScript', TRUE, 9),
       ('Node.js', TRUE, 9),
       ('HTML', TRUE, 9),
       ('CSS', TRUE, 9),
       ('Waterfall', TRUE, 10),
       ('Agile', TRUE, 10),
       ('Prometheus', TRUE, 11),
       ('Grafana', TRUE, 11),
       ('Zabbix', TRUE, 11),
       ('PostgreSQL', TRUE, 12),
       ('MySQL', TRUE, 12),
       ('MongoDB', TRUE, 12),
       ('Kibana', TRUE, 13),
       ('ELK', TRUE, 13),
       ('SLF4J', TRUE, 13),
       ('LOG4J', TRUE, 13),
       ('Logging', TRUE, 13),
       ('Loguru', TRUE, 13),
       ('Docker', TRUE, 14),
       ('Kubernetes ', TRUE, 14),
       ('Openshift', TRUE, 14),
       ('Swagger', TRUE, 15),
       ('Баг-репорты', TRUE, 15),
       ('Test-cases', TRUE, 15),
       ('Git', TRUE, 16),
       ('TeamCity', TRUE, 16),
       ('Ansible', TRUE, 16),
       ('Terraform', TRUE, 16),
       ('GitLab', TRUE, 16),
       ('GitHub', TRUE, 16),
       ('Jenkins', TRUE, 16),
       ('Linux', TRUE, 17),
       ('Windows', TRUE, 17),
       ('Unix', TRUE, 17),
       ('Kafka', TRUE, 18),
       ('RabbitMQ', TRUE, 18),
       ('Spring', TRUE, 19),
       ('Hibernate', TRUE, 19),
       ('Maven', TRUE, 19),
       ('Gradle', TRUE, 19),
       ('Django', TRUE, 19),
       ('Flask', TRUE, 19),
       ('CherryPy', TRUE, 19),
       ('Angular', TRUE, 19),
       ('React', TRUE, 19),
       ('Vue', TRUE, 19),
       ('Postman', TRUE, 20),
       ('SoapUI', TRUE, 20),
       ('REST-assured', TRUE, 20),
       ('TestNG', TRUE, 20),
       ('jUnit', TRUE, 20),
       ('Mockito', TRUE, 20),
       ('Robot', TRUE, 20),
       ('PyUnit', TRUE, 20),
       ('Android Studio', TRUE, 20),
       ('Appium', TRUE, 20),
       ('Espresso ', TRUE, 20),
       ('XCTest', TRUE, 20),
       ('Jest', TRUE, 20),
       ('Mocha/Chai', TRUE, 20),
       ('Cypress', TRUE, 20),
       ('Code Coverage', TRUE, 20),
       ('Поиск и анализ информации',FALSE,21),
       ('Логическое мышление',FALSE,21),
       ('Креативное мышление',FALSE,21),
       ('Системное мышление',FALSE,21),
       ('Выработка и принятие решений',FALSE,21),
       ('Стратегическое мышление',FALSE,21),
       ('Управление временем',FALSE,22),
       ('Управление развитием',FALSE,22),
       ('Эмоциональный интеллект',FALSE,22),
       ('Управление стрессом',FALSE,22),
       ('Энергичность',FALSE,22),
       ('Обратная связь',FALSE,22),
       ('Умение слушать',FALSE,23),
       ('Убеждение и аргументация',FALSE,23),
       ('Нетворкинг',FALSE,23),
       ('Деловое письмо',FALSE,23),
       ('Самопрезентация',FALSE,23),
       ('Разработка презентаций',FALSE,23),
       ('Публичные выступления',FALSE,23),
       ('Командная работа',FALSE,23),
       ('Нацеленность на результат',FALSE,23),
       ('Клиенто-ориентированность',FALSE,23),
       ('Ведение переговоров',FALSE,23),
       ('Организация мероприятий',FALSE,23),
       ('Фасилитация',FALSE,23),
       ('Планирование',FALSE,24),
       ('Управление проектами',FALSE,24),
       ('Управление продуктами',FALSE,24),
       ('Управление людьми',FALSE,24),
       ('Управление ресурсами',FALSE,24),
       ('Управление бюджетом',FALSE,24),
       ('Постановка задачи и делегирование',FALSE,24),
       ('Лидерство и мотивация',FALSE,24),
       ('Контроль реализации задач',FALSE,24),
       ('Наставничество',FALSE,24),
       ('Управление изменениями',FALSE,24);