CREATE TABLE IF NOT EXISTS t_workers
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    badge           BIGINT UNIQUE,
    last_name       VARCHAR(50)                            NOT NULL,
    first_name      VARCHAR(50)                            NOT NULL,
    middle_name     VARCHAR(50)                            NOT NULL,
    birthday        VARCHAR(20)                            NOT NULL,
    city            VARCHAR(50)                            NOT NULL,
    email           VARCHAR(50)                            NOT NULL UNIQUE,
    password        VARCHAR(255)                           NOT NULL,
    phone           VARCHAR(50)                            NOT NULL,

    system_level_id BIGINT REFERENCES t_system_levels (id) NOT NULL
);