CREATE TABLE IF NOT EXISTS t_competencies
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    competencion_name VARCHAR(50) UNIQUE                  NOT NULL,
    is_hard           BOOLEAN                             NOT NULL,

    category_id       BIGINT REFERENCES t_categories (id) NOT NULL
);