CREATE TABLE IF NOT EXISTS t_workers_soft_skills
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    worker_id       BIGINT REFERENCES t_workers (id)      NOT NULL,
    competencion_id BIGINT REFERENCES t_competencies (id) NOT NULL,

    UNIQUE (worker_id, competencion_id)
);